exclude: '.*/vendor/.*'
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.4.2
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=128']
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
            exclude: fixtures/.*
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
            # CloudFormation templates rely on macros which will fail a simple
            # YAML load, which is why we have cfn-python-lint enabled below:
            exclude: cloudformation/.*
          - id: debug-statements
          - id: detect-aws-credentials
            args: ['--allow-missing-credentials']
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: pretty-format-json
            args: ['--autofix', '--no-sort-keys', '--indent=4']
            exclude: fixtures/.*
          - id: trailing-whitespace
    - repo: https://github.com/prettier/prettier
      rev: 1.18.2
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md|yaml|yml)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v6.6.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@6.4.0
                - eslint-plugin-prettier@3.1.1
                - prettier@1.18.2
                - eslint-plugin-unicorn@11.0.2
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - stylelint@11.0.0
                - stylelint-config-prettier@6.0.0
                - stylelint-config-recommended@3.0.0
    - repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.35.0
      hooks:
          - id: cfn-python-lint
            files: cloudformation/.*\.(json|yml|yaml)$
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
          - id: bandit
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.27.0
      hooks:
          - id: terraform_fmt
